# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python versions testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        os: [ubuntu-latest]
#         os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: install poetry
      uses: abatilo/actions-poetry@v2.0.0
    - name: install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
